services:
  gateway:
    image: $ORKUZTECH_GATEWAY
    ports:
      - "8090:9999"
    expose:
      - "8090"
    container_name: gateway
    networks:
      - localnetwork
networks:
  localnetwork:
    name: local-network
    external: true