services:

  gateway:
    image: orkuztech/gateway:dev1
    ports:
      - "8090:9999"
    expose:
      - "8090"
    container_name: gateway
    networks:
      - localnetwork

  hello-web-api:
    image: orkuztech/hello-web-api
    container_name: hello_web_api
    networks:
      - localnetwork
      
  hello-flask:
    image: orkuztech/hello-flask
    container_name: hello_flask
    networks:
      - localnetwork
      
networks:
  localnetwork:
    name: local-network