services:
  gateway:
    image: $ORKUZTECH_GATEWAY
    ports:
      - "8090:9999"
    expose:
      - "8090"
    container_name: gateway
    network_mode: "host"
    networks: 
      - ext
networks:
  ext:
    external: true
    name: host