services:

  gateway:
    image: $ORKUZTECH_GATEWAY
    ports:
      - "8090:9999"
    expose:
      - "8090"
    container_name: gateway
    networks:
      - localnetwork

  hello-web-api:
    image: $ORKUZTECH_HELLO_WEB_API
    container_name: hello_web_api
    networks:
      - localnetwork
      
  hello-flask:
    image: $ORKUZTECH_HELLO_FLASK
    container_name: hello_flask
    networks:
      - localnetwork
      
networks:
  localnetwork:
    name: local-network